version: 2

sources:
  - name: sourcesais
    database: SHIPS_DATA
    schema:  snowpipeschema
    tables:
      - name: globalSHIPSTATICROWDATA
      - name: SHIPDYNAMICROWDATA

  - name: sources
    database: SHIPS_DATA
    schema: rowdataschema
    tables:
    - name: Ports
    - name: RawShipsConsoOr